import http from "node:http"; import fs from "node:fs"; import path from "node:path";
const ROOT=process.env.LH_ROOT, SEITE=process.argv[2]||"modell.html", ZIEL=process.argv[3];
const MIME={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".webp":"image/webp",".jpg":"image/jpeg",".ico":"image/x-icon",".txt":"text/plain",".webmanifest":"application/manifest+json"};
const s=http.createServer((q,r)=>{let p=decodeURIComponent(q.url.split("?")[0]); if(p==="/")p="/index.html";
 const fp=path.join(ROOT,p);
 if(!fp.startsWith(ROOT)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){console.log("  404:",p);r.writeHead(404);r.end();return;}
 r.writeHead(200,{"content-type":MIME[path.extname(fp)]||"application/octet-stream"}); r.end(fs.readFileSync(fp));});
await new Promise(r=>s.listen(0,r));
const base=`http://127.0.0.1:${s.address().port}`;
const pw=await import("playwright-core");
const b=await pw.chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-sandbox","--use-gl=swiftshader","--enable-unsafe-swrast"]});
const page=await b.newPage({viewport:{width:1280,height:700},deviceScaleFactor:1});
page.on("requestfailed",q=>console.log("  FEHLT:",q.url().replace(base,"")));
await page.goto(`${base}/${SEITE}`,{waitUntil:"load"});
const info=await page.evaluate(()=>{const e=document.querySelector('.page-banner');
  if(!e) return 'kein .page-banner';
  const cs=getComputedStyle(e);
  return {art:e.style.getPropertyValue('--art')||'(leer)', hintergrund:cs.backgroundImage.slice(0,160)};});
console.log(" .page-banner:",JSON.stringify(info));
await page.waitForTimeout(1500);
await page.screenshot({path:ZIEL,clip:{x:0,y:0,width:1280,height:400}});
await b.close(); s.close(); process.exit(0);
